language: python
python:
- '3.5'
- '3.6'
install:
- pip3 install -r requirements.txt
script:
- python3 -m flake8
- python3 -m pytest

deploy:
  provide: pypi
  user: tomkukral
  on:
    tags: true
    repo: tomkukral/kib
