---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.k8s.6shore.net
spec:
  group: k8s.6shore.net
  version: v1
  scope: Namespaced
  names:
    plural: images
    singular: image
    kind: Image
    shortNames:
      - im
